const petData = [
  {
    name: "Baxter",
    img: "./images/Baxter.webp",
    type: "Dog",
    breed: "Beagle",
    sex: "Male",
    color: "Tri-color (Black, Brown, White)",
    spayedNeutered: "Yes",
    age: "5 Years",
    animalID: "34621",
    microchipNumber: "982000364789210",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
  },
  {
    name: "Luna",
    img: "./images/mainecooncat.webp",
    type: "Cat",
    breed: "Maine Coon",
    sex: "Female",
    color: "Grey with white markings",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "57281",
    microchipNumber: "981120019776432",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings. She was found as a stray and has since become a gentle and affectionate companion. Luna enjoys perching on windowsills, watching birds, and being the center of attention. She's a bit shy at first but warms up quickly, especially if you have treats! Luna would thrive in a calm environment where she can relax and be pampered like the queen she is.",
  },
  {
    name: "Sandy",
    img: "./images/goldendog.jpeg",
    type: "Dog",
    breed: "Golden Retriever",
    sex: "Female",
    color: "Golden",
    spayedNeutered: "Yes",
    age: "7 Years",
    animalID: "41382",
    microchipNumber: "985112004567890",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Sandy is a heartwarming Golden Retriever with a golden coat as bright as her personality. Rescued from a neglectful situation, she has shown incredible resilience and love for life. Sandy is great with children and other pets, making her an ideal family dog. She enjoys outdoor adventures, especially swimming and fetching. Sandy is looking for a forever home where she can spread her joy and love.",
  },
  {
    name: "Oliver",
    img: "./images/siamesecat.webp",
    type: "Cat",
    breed: "Siamese",
    sex: "Male",
    color: "Seal Point",
    spayedNeutered: "Yes",
    age: "2 Years",
    animalID: "62894",
    microchipNumber: "981120025678902",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Oliver is a sleek Siamese cat with striking blue eyes and a seal point coat. Found wandering in a neighborhood, he's adapted well to shelter life but is eager for a permanent home. Oliver is vocal, expressing his thoughts freely, and enjoys interactive playtime. He's affectionate and loves to be close to his human companions, often following them around the house. Oliver would do best in a home where he can receive plenty of attention and love.",
  },
  {
    name: "Max",
    img: "./images/labradorretriever.jpeg",
    type: "Dog",
    breed: "Labrador Retriever",
    sex: "Male",
    color: "Chocolate",
    spayedNeutered: "Yes",
    age: "4 Years",
    animalID: "47920",
    microchipNumber: "985120031478902",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Max is a charming Chocolate Labrador with a love for life and a tail that never stops wagging. Rescued from an overcrowded shelter, Max has shown immense gratitude and loyalty to his caregivers. He is full of energy and would thrive in a home with a backyard or regular access to outdoor activities. Max is great with children and other dogs, and he's always up for a game of fetch or a leisurely walk. His ideal home would be with an active family who can match his energy and zest for life.",
  },
  {
    name: "Daisy",
    img: "./images/persiancat.jpeg",
    type: "Cat",
    breed: "Persian",
    sex: "Female",
    color: "White",
    spayedNeutered: "Yes",
    age: "6 Years",
    animalID: "58329",
    microchipNumber: "981120036712345",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Daisy is a stunning white Persian cat with a luxurious coat and gentle demeanor. She was surrendered by an owner who could no longer care for her. Daisy is a bit of a diva and loves being the center of attention. She enjoys being groomed and will happily sit in your lap for hours. She's not fond of loud noises or fast movements, so a quiet and calm household would be ideal. Daisy is looking for a loving home where she can be pampered and adored.",
  },
  {
    name: "Charlie",
    img: "./images/dachshunddog.jpeg",
    type: "Dog",
    breed: "Dachshund",
    sex: "Male",
    color: "Dapple (Black and Gray)",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "49583",
    microchipNumber: "982000367829101",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Charlie is a spirited Dapple Dachshund with a playful personality. He was found as a stray and has since shown an incredible zest for life. Charlie loves exploring, whether it's a new trail or the corners of his home. He's a bit mischievous and enjoys hiding his toys. Charlie would do well in a home with an individual or family who enjoys fun and adventure. He's small but has a big heart and a lot of love to give.",
  },
  {
    name: "George",
    img: "./images/britishshorthaircat.jpeg",
    type: "Cat",
    breed: "British Shorthair",
    sex: "Male",
    color: "Blue (Gray)",
    spayedNeutered: "Yes",
    age: "4 Years",
    animalID: "61029",
    microchipNumber: "985112007651234",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "George is a robust British Shorthair with a striking blue-gray coat and a calm, dignified demeanor. Rescued from a busy city environment, he's adapted well to a quieter life. George enjoys leisurely days, lounging in sunny spots, and watching the world go by. He's not overly demanding for attention but appreciates a good chin scratch and will purr loudly in response. George is a bit reserved at first but becomes a loyal companion once he feels comfortable. He would be perfect for someone seeking a low-maintenance, independent cat.",
  },
  {
    name: "Bella",
    img: "./images/boxerdog.webp",
    type: "Dog",
    breed: "Boxer",
    sex: "Female",
    color: "Fawn with white markings",
    spayedNeutered: "Yes",
    age: "6 Years",
    animalID: "50824",
    microchipNumber: "982000360234567",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Bella is a spirited Boxer with a fawn coat and charming white markings. She was rescued from a neglectful situation and has shown immense love and gratitude to her caregivers. Bella is energetic and playful, enjoying activities like running and playing fetch. She's great with older children and would thrive in a home where she can be active and engaged. Bella has a big personality and would be a fantastic companion for someone who loves adventure and fun.",
  },
  {
    name: "Sophie",
    img: "./images/ragdollcat.png",
    type: "Cat",
    breed: "Ragdoll",
    sex: "Female",
    color: "Seal point with blue eyes",
    spayedNeutered: "Yes",
    age: "1 Year",
    animalID: "63845",
    microchipNumber: "985112008765432",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Sophie is a young Ragdoll cat with a soft seal point coat and mesmerizing blue eyes. She was found as a kitten and raised in a foster home. Sophie is incredibly affectionate, often seeking out laps to curl up in. She's playful and enjoys interactive toys, but she's also content to relax and watch the world go by. Sophie gets along well with other pets and would be an excellent addition to a loving family or individual looking for a gentle and loving companion.",
  },
  {
    name: "Buddy",
    img: "./images/goldenretriever.jpg",
    type: "Dog",
    breed: "Golden Retriever",
    sex: "Male",
    color: "Golden",
    spayedNeutered: "Yes",
    age: "5 Years",
    animalID: "48276",
    microchipNumber: "982000367823456",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Buddy is a lovable Golden Retriever with a heart of gold. He was surrendered by his previous owners due to a change in living situation, but he's now ready to find his forever home. Buddy is gentle, patient, and great with children. He loves to play fetch and go for long walks. With his friendly personality and endless affection, Buddy would make the perfect family dog.",
  },
  {
    name: "Cleo",
    img: "./images/bengalcat.jpg",
    type: "Cat",
    breed: "Bengal",
    sex: "Female",
    color: "Brown with black rosettes",
    spayedNeutered: "Yes",
    age: "2 Years",
    animalID: "60178",
    microchipNumber: "985112009876543",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Cleo is a stunning Bengal cat with a beautiful, wild-looking coat and captivating green eyes. She was rescued from a neglectful situation but has since blossomed into a confident and playful feline. Cleo loves to explore and engage in interactive play sessions. She's intelligent and enjoys challenging toys that stimulate her mind. With her exotic appearance and affectionate nature, Cleo would make an excellent companion for an experienced cat owner.",
  },
  {
    name: "Rufus",
    img: "./images/frenchbulldog.jpg",
    type: "Dog",
    breed: "French Bulldog",
    sex: "Male",
    color: "Brindle",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "53629",
    microchipNumber: "982000367829012",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Rufus is a charming French Bulldog with a brindle coat and a big personality. He was surrendered by his previous owners due to a job relocation. Rufus is a goofy and affectionate companion who loves to cuddle and play. He's great with children and other pets, and he's always up for a game of tug-of-war. With his lovable antics and loyal nature, Rufus would make an excellent addition to any family.",
  },
  {
    name: "Willow",
    img: "./images/russianbluecat.jpg",
    type: "Cat",
    breed: "Russian Blue",
    sex: "Female",
    color: "Silver-blue",
    spayedNeutered: "Yes",
    age: "4 Years",
    animalID: "57492",
    microchipNumber: "985112001234567",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Willow is a beautiful Russian Blue cat with a sleek, silver-blue coat and captivating green eyes. She was found as a stray and has since become a calm and gentle companion. Willow is independent but enjoys spending time with her human companions, often following them around the house. She's not overly demanding but appreciates a good lap to curl up on. With her elegant appearance and sweet nature, Willow would be a lovely addition to a quiet household.",
  },
  {
    name: "Cooper",
    img: "./images/australiancattledog.jpg",
    type: "Dog",
    breed: "Australian Cattle Dog",
    sex: "Male",
    color: "Blue Heeler",
    spayedNeutered: "Yes",
    age: "6 Years",
    animalID: "46315",
    microchipNumber: "982000367823789",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Cooper is an energetic Australian Cattle Dog with a striking blue heeler coat. He was surrendered by his previous owners due to a change in living situation. Cooper is an intelligent and hardworking breed, thriving on physical and mental stimulation. He excels at agility training and loves to learn new tricks. With his loyal and protective nature, Cooper would make an excellent companion for an active individual or family who can provide him with plenty of exercise and enrichment.",
  },
  {
    name: "Misty",
    img: "./images/norwegianforestcat.jpg",
    type: "Cat",
    breed: "Norwegian Forest Cat",
    sex: "Female",
    color: "Grey with white markings",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "59027",
    microchipNumber: "985112007654321",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Misty is a majestic Norwegian Forest Cat with a long, fluffy grey coat and striking white markings. She was found as a stray and has since become a friendly and affectionate companion. Misty loves to play and is especially fond of chasing toys that mimic the movements of prey. She's also a skilled climber and enjoys perching on high surfaces. With her stunning appearance and playful nature, Misty would make an excellent addition to a family that can provide her with plenty of attention and playtime.",
  },
  {
    name: "Diesel",
    img: "./images/germanshepherddog.jpg",
    type: "Dog",
    breed: "German Shepherd",
    sex: "Male",
    color: "Black and Tan",
    spayedNeutered: "Yes",
    age: "4 Years",
    animalID: "51836",
    microchipNumber: "982000367829456",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Diesel is a loyal and intelligent German Shepherd with a striking black and tan coat. He was rescued from a neglectful situation but has shown incredible resilience and a desire to please. Diesel is highly trainable and excels at obedience exercises. He's protective yet gentle with his family and would make an excellent watchdog. With his dedication and loving nature, Diesel would thrive in a home with experienced dog owners who can provide him with the guidance and structure he needs.",
  },
  {
    name: "Lulu",
    img: "./images/exoticshorthaircat.jpg",
    type: "Cat",
    breed: "Exotic Shorthair",
    sex: "Female",
    color: "Blue (Gray)",
    spayedNeutered: "Yes",
    age: "2 Years",
    animalID: "62037",
    microchipNumber: "985112009012345",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Lulu is an adorable Exotic Shorthair cat with a plush, blue-gray coat and a sweet, laid-back personality. She was surrendered by her previous owners due to a change in living situation. Lulu loves to cuddle and will happily spend hours napping on your lap or next to you on the couch. She's a bit shy at first but quickly warms up to her human companions. With her cute appearance and affectionate nature, Lulu would make an excellent companion for someone seeking a calm and loving feline friend.",
  },
  {
    name: "Teddy",
    img: "./images/chowchowdog.jpg",
    type: "Dog",
    breed: "Chow Chow",
    sex: "Male",
    color: "Red",
    spayedNeutered: "Yes",
    age: "5 Years",
    animalID: "47619",
    microchipNumber: "982000367829678",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Teddy is a majestic Chow Chow with a stunning red coat and a regal demeanor. He was surrendered by his previous owners due to a change in living situation. Teddy is a loyal and protective breed, forming strong bonds with his family. He's great with children and enjoys spending time outdoors, but he also loves to relax and lounge around the house. With his impressive appearance and affectionate nature, Teddy would make an excellent companion for a family that can provide him with the attention and exercise he needs.",
  },
  {
    name: "Sasha",
    img: "./images/orientalshorthaircat.jpg",
    type: "Cat",
    breed: "Oriental Shorthair",
    sex: "Female",
    color: "Ebony",
    spayedNeutered: "Yes",
    age: "1 Year",
    animalID: "64208",
    microchipNumber: "985112001122334",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Sasha is a playful and energetic Oriental Shorthair with a sleek ebony coat and striking green eyes. She was found as a kitten and raised in a foster home. Sasha loves to explore and engage in interactive play sessions. She's highly intelligent and enjoys challenging toys that stimulate her mind. With her curious nature and affectionate personality, Sasha would make an excellent companion for someone who can provide her with plenty of mental stimulation and playtime.",
  },
  {
    name: "Jax",
    img: "./images/pittbulldog.jpg",
    type: "Dog",
    breed: "Pit Bull Terrier",
    sex: "Male",
    color: "Brindle",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "54729",
    microchipNumber: "982000367823456",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Jax is a lovable Pit Bull Terrier with a brindle coat and a gentle demeanor. He was rescued from an overcrowded shelter and has since blossomed into a loyal and affectionate companion. Jax is great with children and loves to play fetch and go for long walks. He's highly trainable and eager to please, making him an excellent candidate for obedience training. With his friendly personality and endless affection, Jax would make a wonderful addition to an active family.",
  },
  {
    name: "Cali",
    img: "./images/calicoshorthaircat.jpg",
    type: "Cat",
    breed: "Calico Shorthair",
    sex: "Female",
    color: "Calico (White, Orange, and Black)",
    spayedNeutered: "Yes",
    age: "4 Years",
    animalID: "56341",
    microchipNumber: "985112005678901",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Cali is a stunning Calico Shorthair with a tri-color coat of white, orange, and black. She was found as a stray and has since become a friendly and affectionate companion. Cali loves to play and is especially fond of chasing toys that mimic the movements of prey. She's also a skilled climber and enjoys perching on high surfaces. With her beautiful appearance and playful nature, Cali would make an excellent addition to a family that can provide her with plenty of attention and playtime.",
  },
  {
    name: "Duke",
    img: "./images/bulldogdog.jpg",
    type: "Dog",
    breed: "Bulldog",
    sex: "Male",
    color: "Brindle",
    spayedNeutered: "Yes",
    age: "6 Years",
    animalID: "45672",
    microchipNumber: "982000367825678",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Duke is a lovable Bulldog with a brindle coat and a gentle, laid-back personality. He was surrendered by his previous owners due to a change in living situation. Duke is a loyal and affectionate companion who loves to cuddle and spend time with his family. He's great with children and other pets, and he's always up for a leisurely stroll or a nap on the couch. With his friendly nature and easy-going demeanor, Duke would make an excellent addition to any household.",
  },
  {
    name: "Luna",
    img: "./images/ragamuffincat.jpg",
    type: "Cat",
    breed: "Ragamuffin",
    sex: "Female",
    color: "Seal Point",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "58904",
    microchipNumber: "985112002233445",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Luna is a beautiful Ragamuffin cat with a soft, fluffy seal point coat and mesmerizing blue eyes. She was found as a stray and has since become a friendly and affectionate companion. Luna loves to play and is especially fond of interactive toys that mimic the movements of prey. She's also a skilled climber and enjoys perching on high surfaces. With her stunning appearance and playful nature, Luna would make an excellent addition to a family that can provide her with plenty of attention and playtime.",
  },
  {
    name: "Marley",
    img: "./images/pitbullterrier.jpg",
    type: "Dog",
    breed: "Pit Bull Terrier",
    sex: "Female",
    color: "Brindle",
    spayedNeutered: "Yes",
    age: "2 Years",
    animalID: "61357",
    microchipNumber: "982000367823789",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Marley is a playful and energetic Pit Bull Terrier with a brindle coat and a friendly personality. She was rescued from an overcrowded shelter and has since blossomed into a loyal and affectionate companion. Marley loves to play fetch and go for long walks. She's highly trainable and eager to please, making her an excellent candidate for obedience training. With her friendly nature and endless energy, Marley would make a wonderful addition to an active family.",
  },
  {
    name: "Penny",
    img: "./images/beagledog.jpg",
    type: "Dog",
    breed: "Beagle",
    sex: "Female",
    color: "Tri-color (Black, Brown, White)",
    spayedNeutered: "Yes",
    age: "4 Years",
    animalID: "52841",
    microchipNumber: "982000367826789",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Penny is a lovable Beagle with a tri-color coat and a friendly, energetic personality. She was surrendered by her previous owners due to a change in living situation. Penny loves to play and is always up for a game of fetch or a long walk. She's great with children and other pets, and her adorable howls are sure to bring a smile to your face. With her affectionate nature and endless curiosity, Penny would make an excellent companion for an active family.",
  },
  {
    name: "Winston",
    img: "./images/britishshorthaircat.jpg",
    type: "Cat",
    breed: "British Shorthair",
    sex: "Male",
    color: "Blue (Gray)",
    spayedNeutered: "Yes",
    age: "5 Years",
    animalID: "49376",
    microchipNumber: "985112003456789",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Winston is a regal British Shorthair cat with a plush blue-gray coat and a calm, dignified demeanor. He was found as a stray and has since become a loyal and affectionate companion. Winston enjoys spending quiet days lounging in sunny spots and observing the world around him. He's not overly demanding but appreciates a good lap to curl up on. With his elegant appearance and sweet nature, Winston would make an excellent addition to a quiet household.",
  },
  {
    name: "Nala",
    img: "./images/siamesemixcat.jpg",
    type: "Cat",
    breed: "Siamese Mix",
    sex: "Female",
    color: "Seal Point with Blue Eyes",
    spayedNeutered: "Yes",
    age: "3 Years",
    animalID: "57293",
    microchipNumber: "985112007890123",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Nala is a beautiful Siamese mix with a sleek seal point coat and captivating blue eyes. She was found as a stray and has since become a friendly and affectionate companion. Nala loves to play and is especially fond of interactive toys that mimic the movements of prey. She's also a skilled climber and enjoys perching on high surfaces. With her stunning appearance and playful nature, Nala would make an excellent addition to a family that can provide her with plenty of attention and playtime.",
  },
  {
    name: "Zeke",
    img: "./images/rhodesianridgebackdog.jpg",
    type: "Dog",
    breed: "Rhodesian Ridgeback",
    sex: "Male",
    color: "Wheaten",
    spayedNeutered: "Yes",
    age: "6 Years",
    animalID: "46819",
    microchipNumber: "982000367824567",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Zeke is a majestic Rhodesian Ridgeback with a striking wheaten coat and a regal demeanor. He was surrendered by his previous owners due to a change in living situation. Zeke is a loyal and protective breed, forming strong bonds with his family. He's great with children and enjoys spending time outdoors, but he also loves to relax and lounge around the house. With his impressive appearance and affectionate nature, Zeke would make an excellent companion for a family that can provide him with the attention and exercise he needs.",
  },
  {
    name: "Piper",
    img: "./images/sphynxcat.jpg",
    type: "Cat",
    breed: "Sphynx",
    sex: "Female",
    color: "Naked (Light Skin)",
    spayedNeutered: "Yes",
    age: "2 Years",
    animalID: "60482",
    microchipNumber: "985112004567890",
    status: [
      "Health checked.",
      "Vaccinations up to date.",
      "Regularly dewormed.",
      "Microchipped.",
    ],
    about:
      "Piper is a unique Sphynx cat with a warm, affectionate personality and a distinctive hairless appearance. She was surrendered by her previous owners due to a change in living situation. Piper loves to cuddle and will happily spend hours snuggled up next to her human companions. She's highly energetic and enjoys interactive play sessions, but she's also content to relax and soak up the attention. With her quirky looks and loving nature, Piper would make an excellent companion for someone seeking a one-of-a-kind feline friend.",
  },
];
